src/DotNetCoreIdentity.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DotNetCoreIdentity.Web.Models;
using Microsoft.AspNetCore.Authorization;

namespace DotNetCoreIdentity.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/DotNetCoreIdentity.Web/ViewComponents/PostListViewComponent.cs
using DotNetCoreIdentity.Application.BlogServices;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DotNetCoreIdentity.Web.ViewComponents
{
    [ViewComponent]
    public class PostListViewComponent : ViewComponent
    {
        private readonly IPostService _postService;
        public PostListViewComponent(IPostService postService)
        {
            _postService = postService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var postList = await _postService.GetAll();
           
            return View(postList.Result);
        }
     
    }
}

src/DotNetCoreIdentity.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    @if (User.Identity.IsAuthenticated)
    {
        <h1>Giriş Yaptınız :)</h1>
    }
        <div class="container">
            @await Component.InvokeAsync("PostList")
        </div>
</div>