src/DotNetCoreIdentity.Web/Areas/CMS/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DotNetCoreIdentity.Application;
using DotNetCoreIdentity.Application.CategoryServices.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DotNetCoreIdentity.Web.Areas.CMS.Controllers
{
    [Authorize(Roles = "Admin, Editor")]
    [Area("CMS")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var getAllService = await _categoryService.GetAll();
            return View(getAllService.Result);
        }
        public async Task<IActionResult> Details(int id)
        {
            var getService = await _categoryService.Get(id);
            return View(getService.Result);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryInput model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedById = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                model.CreatedBy = User.FindFirst(ClaimTypes.Name).Value;

                var result = await _categoryService.Create(model);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, result.ErrorMessage);

            }
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var getService = await _categoryService.Get(id);
            return View(getService.Result);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id, CategoryDto model)
        {
            if (ModelState.IsValid)
            {
                var deleteService = await _categoryService.Delete(id);
                if (deleteService.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, deleteService.ErrorMessage);
                }
            }
            return View(model);
        }

        public async Task<IActionResult> Update(int id)
        {
            var getService = await _categoryService.Get(id);
            UpdateCategoryInput input = new UpdateCategoryInput
            {
                Id = getService.Result.Id,
                CreatedById = getService.Result.CreatedById,
                ModifiedById = User.FindFirst(ClaimTypes.NameIdentifier).Value,
                Name = getService.Result.Name,
                UrlName = getService.Result.UrlName
            };
            return View(input);
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateCategoryInput model)
        {
            if (ModelState.IsValid)
            {
                var getService = await _categoryService.Get(id);
                model.CreatedById = getService.Result.CreatedById;
                model.CreatedBy = getService.Result.CreatedBy;

                model.Id = getService.Result.Id;
                model.ModifiedById = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                model.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;

                var updateService = await _categoryService.Update(model);
                if (updateService.Succeeded)
                {
                    return RedirectToAction("Details", new { id });
                }
                ModelState.AddModelError(string.Empty, updateService.ErrorMessage);
            }
            return View(model);
        }
    }
}

src/DotNetCoreIdentity.Web/Areas/CMS/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DotNetCoreIdentity.Application;
using DotNetCoreIdentity.Application.BlogServices;
using DotNetCoreIdentity.Application.BlogServices.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;

namespace DotNetCoreIdentity.Web.CMS.Controllers
{
    [Authorize(Roles = "Admin,Editor")]
    [Area("CMS")]
    public class PostController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICategoryService _categoryService;
        private readonly IFileProvider _fileProvider;
        private readonly IHostingEnvironment _env;


        public PostController(IPostService postService, ICategoryService categoryService, IFileProvider fileProvider, IHostingEnvironment env)
        {
            _postService = postService;
            _categoryService = categoryService;
            _fileProvider = fileProvider;
            _env = env;
        }
        // liste
        public async Task<IActionResult> Index()
        {
            var getAllService = await _postService.GetAll();
            List<PostDto> model = getAllService.Result;
            return View(model);
        }
        public async Task<IActionResult> Details(Guid id)
        {
            ApplicationResult<PostDto> data = await _postService.Get(id);
            return View(data.Result);
        }
        public async Task<IActionResult> Create()
        {
            var categoryList = await _categoryService.GetAll();
            ViewBag.CategoryDDL = categoryList.Result.Select(x => new SelectListItem
            {
                Selected = false,
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreatePostInput model)
        {
            if (ModelState.IsValid)
            {
                // createdById alanini doldur
                model.CreatedById = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                model.CreatedBy = User.FindFirst(ClaimTypes.Name).Value;
                // createService e gonder
                var createService = await _postService.Create(model);
                // hata yoksa Index e redirect et
                if (createService.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                // hata varsa hatayi ModelState e ekle
                ModelState.AddModelError(string.Empty, createService.ErrorMessage);
            }
            var categoryList = await _categoryService.GetAll();
            ViewBag.CategoryDDL = categoryList.Result.Select(x => new SelectListItem
            {
                Selected = false,
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();
            return View(model);
        }
        public async Task<IActionResult> Update(Guid id)
        {
            var post = await _postService.Get(id);
            var categoryList = await _categoryService.GetAll();
            ViewBag.CategoryDDL = categoryList.Result.Select(c => new SelectListItem
            {
                Selected = false,
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();
            UpdatePostInput model = new UpdatePostInput
            {
                Id = post.Result.Id,
                CategoryId = post.Result.CategoryId,
                Content = post.Result.Content,
                Title = post.Result.Title,
                UrlName = post.Result.UrlName,
                CreatedById = post.Result.CreatedById
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Guid id, UpdatePostInput model)
        {
            if (ModelState.IsValid)
            {
                if (id != model.Id)
                {
                    ModelState.AddModelError(string.Empty, "Forma müdahele etme!");
                }
                else
                {
                    model.ModifiedById = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    model.ModifiedBy = User.FindFirst(ClaimTypes.Name).Value;

                    var updatePost = await _postService.Update(model);
                    if (updatePost.Succeeded)
                    {
                        return RedirectToAction("Details", new { id = model.Id });
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Bir hata olustu:\n" + updatePost.ErrorMessage);
                    }
                }
            }
            var categoryList = await _categoryService.GetAll();
            ViewBag.CategoryDDL = categoryList.Result.Select(c => new SelectListItem
            {
                Selected = false,
                Value = c.Id.ToString(),
                Text = c.Name
            }).ToList();
            return View(model);
        }
        public async Task<IActionResult> Delete(Guid id)
        {
            var model = await _postService.Get(id);
            return View(model.Result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id, PostDto input)
        {
            if (ModelState.IsValid && id == input.Id)
            {
                var delete = await _postService.Delete(id);
                if (delete.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            ModelState.AddModelError(string.Empty, "Bir hata olustu");
            return View(input);
        }
        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> DeleteApi([FromBody]PostDeleteDto model)
        {
            var delete = await _postService.Delete(model.Id);
            return Json(delete);
        }
        public async Task<IActionResult> UploadImage(Guid id)
        {
            ApplicationResult<PostDto> data = await _postService.Get(id);
            return View(data.Result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadImage(Guid id, IFormFile file)
        {
            if (file != null || file.Length != 0)
            {
                // resmi al degiskene ata
                FileInfo fi = new FileInfo(file.FileName);
                // bir dosya adi belirle
                var newFileName = id.ToString() + "_" + String.Format("{0:d}", (DateTime.Now.Ticks / 10) % 100000000) + fi.Extension;
                // resmi belirtilen path'e yukle
                var webPath = _env.WebRootPath;
                var path = Path.Combine("", webPath + @"\images\" + newFileName);
                var pathToSave = @"/images/" + newFileName;
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                // yukleme tamamlandiktan sonra resmin yolunu db'ye yukle (imageUrl alanini olustur)
                var updateUrl = await _postService.UpdateImageUrl(id, pathToSave);
                if (updateUrl.Succeeded)
                {
                    return RedirectToAction("UploadImage", new { id });
                }

            }

            return RedirectToAction("Error", "Home");
        }

    }
}

src/DotNetCoreIdentity.Web/Areas/CMS/Views/Post/Create.cshtml
@model DotNetCoreIdentity.Application.BlogServices.Dtos.CreatePostInput

@{
    ViewData["Title"] = "Create";
    Layout = "/Views/Shared/_Layout.cshtml";

}
<link href="~/lib/froala-editor/css/froala_editor.pkgd.min.css" rel="stylesheet" type="text/css" />

<h1>Create</h1>

<h4>CreatePostInput</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create" id="create-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" id="blog-content"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <textarea id="blog-content-2"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="UrlName" class="control-label"></label>
                <input asp-for="UrlName" class="form-control" />
                <span asp-validation-for="UrlName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items="ViewBag.CategoryDDL" class="form-control"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <input asp-for="CreatedById" type="hidden" />
            <div class="form-group">
                <input type="submit" onclick="submitForm()" id="submit-form-btn" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/froala-editor/js/froala_editor.pkgd.min.js"></script>


    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function submitForm() {
            $("#submit-form-btn").attr("disabled", "disabled");
            $("#create-form").submit();
        }
        new FroalaEditor("#blog-content");
        
    </script>
}

src/DotNetCoreIdentity.Web/Areas/CMS/Views/Post/Delete.cshtml
@model DotNetCoreIdentity.Application.BlogServices.Dtos.PostDto

@{
    ViewData["Title"] = "Delete";
    Layout = "/Views/Shared/_Layout.cshtml";

}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PostDto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UrlName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UrlName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/DotNetCoreIdentity.Web/Areas/CMS/Views/Post/Details.cshtml
@model DotNetCoreIdentity.Application.BlogServices.Dtos.PostDto

@{
    ViewData["Title"] = "Details";
    Layout = "/Views/Shared/_Layout.cshtml";

}

<h1>Details</h1>

<div>
    <h4>PostDto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UrlName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UrlName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>
      
    </dl>
    <h3>Kategori bilgileri</h3>
    <hr />
    <dl>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category.UrlName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.UrlName)
        </dd>
    </dl>
</div>
<div>
   
    <a asp-action="UploadImage" asp-controller="Post" asp-route-id="@Model.Id">Resim Yukle</a>
    |
    <a asp-action="Index">Back to List</a>
</div>

src/DotNetCoreIdentity.Web/Areas/CMS/Views/Post/Index.cshtml
@model IEnumerable<DotNetCoreIdentity.Application.BlogServices.Dtos.PostDto>

@{
    ViewData["Title"] = "Index";
    Layout = "/Views/Shared/_Layout.cshtml";

}

<p>
    <a asp-action="Create"  class="btn btn-primary mr-3">Yeni Post Oluştur</a>
    <a asp-action="Index" asp-controller="Category" class="btn btn-primary">Kategorileri Yonet</a>

</p>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UrlName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CategoryId)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedBy)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="row-@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UrlName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifiedBy)
                </td>
                <td>
                    <a asp-action="Update" asp-controller="Post" asp-route-id="@item.Id" class="btn btn-sm btn-outline-primary">Güncelle</a>
                    <a asp-action="Details" asp-controller="Post" asp-route-id="@item.Id" class="btn btn-sm btn-outline-primary">Detay</a>
                    <button type="button" class="btn btn-sm btn-outline-primary silme-modal-btn" data-title="@item.Title" data-id="@item.Id">
                        Sil
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>


<!-- Modal -->
<div class="modal fade" id="silmeModal" tabindex="-1" role="dialog" aria-labelledby="silmeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="silmeModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Bu blog post'u silmek istediğinize emin misiniz?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Vazgeç</button>
                <button type="button" class="btn btn-primary" id="confirm-delete" data-id="">Sil</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(".silme-modal-btn").click(function () {
            var id = $(this).attr("data-id");
            $("#confirm-delete").attr("data-id", id);
            var title = $(this).attr("data-title");
            $("#silmeModalLabel").text(title);
            $('#silmeModal').modal('show');
        });

        $("#confirm-delete").click(function () {
            $("#confirm-delete").attr("disabled", "disabled");
            var params = {
                id: $("#confirm-delete").attr("data-id")
            };
            $.ajax({
                url: "/CMS/Post/DeleteApi",
                method: "POST",
                headers: { "content-type": "application/json" },
                data: JSON.stringify(params)
            }).done(function (data) {
                console.log(data);
                checkDeleteStatus(data, params.id);
                alert("silme basarili");
                $("#confirm-delete").removeAttr("disabled");

            });
        });
        function checkDeleteStatus(data, id) {
            $('#silmeModal').modal('hide');
            // silme durumu basariliysa modali kapatacak
            if (data.succeeded) {
                // listeden silinen satiri kaldiracak
                $("#row-" + id).remove();
            }
            else {
                alert(data.errorMessage);
            }
            // hatali ise hata mesajini alert ile verecek
        }
    </script>
}

src/DotNetCoreIdentity.Web/Areas/CMS/Views/Post/Update.cshtml
@model DotNetCoreIdentity.Application.BlogServices.Dtos.UpdatePostInput

@{
    ViewData["Title"] = "Update";
    Layout = "/Views/Shared/_Layout.cshtml";

}

<h1>Update</h1>

<h4>UpdatePostInput</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" id="update-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" rows="10" cols="10" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UrlName" class="control-label"></label>
                <input asp-for="UrlName" class="form-control" />
                <span asp-validation-for="UrlName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" asp-items="ViewBag.CategoryDDL" class="form-control"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <input asp-for="CreatedById" type="hidden" />
            <input asp-for="Id" type="hidden" />
            <div class="form-group">
                <input onclick="submitForm()" id="submit-form-btn" type="submit" value="Güncelle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye dön</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        function submitForm() {
            $("#submit-form-btn").attr("disabled", "disabled");
            $("#update-form").submit();
        }
    </script>
}

src/DotNetCoreIdentity.Web/Areas/CMS/Views/Post/UploadImage.cshtml
@model DotNetCoreIdentity.Application.BlogServices.Dtos.PostDto

@{
    ViewData["Title"] = "Upload Image";
    Layout = "/Views/Shared/_Layout.cshtml";

}

<h1>Upload Image</h1>
<form asp-action="UploadImage" method="post" enctype="multipart/form-data">
    <input type="hidden" name="id" value="@Model.Id" />
    <div class="form-group">
        <div class="col-md-10">
            <p>Bir resim yükle</p>
            <input type="file" name="file" />
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Kaydet" />
    </div>

</form>

<div>
    <h4>Blog Post Detayi</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UrlName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UrlName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.ImageUrl" />
        </dd>

    </dl>
</div>
<div>
    
    <a asp-action="Index">Back to List</a>
</div>